## Data Preprocessing

### Import Necessary Libraries

In [2]:
import sys
sys.path.append('../src')
sys.path.append('../src/data')

import random
import re

import numpy as np
import pandas as pd
from transformers import T5Tokenizer, T5ForConditionalGeneration

from data_loader import DataLoader, DataLoaderSelector
from augment_dataset import (
    add_synthetic_conclusions_straightforward,
    add_synthetic_conclusion_from_temps,
    add_enhanced_synthetic_conclusions,
    preprocess_conclusion
)

### Load and Clean Dataset

In [3]:
mwr = DataLoaderSelector(data_path='data_th_scale.csv')

### Access the Dataframe

In [4]:
mwr_df = mwr.data_loader.data.copy(deep=True)  # full deep copy of raw data

In [5]:
print(mwr_df['r:Th'].value_counts(normalize=True))

r:Th
2    0.294479
1    0.289074
0    0.241170
4    0.080335
5    0.064945
3    0.029997
Name: proportion, dtype: float64

## Generate Synthetic Descriptions

### Straightforward Conclusions

In [5]:
# Th: Thermal asymmetry with:
# 0: no changes
# 1: slightly elevated temperature
# 2: moderately elevated temperature (surface)
# 3: moderately elevated temperature (surface and depth)
# 4: increased temperature (surface and depth), partial asymmetry
# 5: increased temperature (surface and depth), greater and clear asymmetry

In [6]:
# add the straightforward conclusions
mwr_df_simple = add_synthetic_conclusions_straightforward(mwr_df.copy(deep=True))

In [7]:
mwr_df_simple.head()

,Examination ID,Conclusion,r:Th,Weight,Height,Ambient temperature,r:AgeInYears,Mammary diameter,Cycle,Day from the first day,...,R8 sk,L8 sk,R9 sk,L9 sk,T1 sk,T2 sk,R0 sk,L0 sk,Conclusion (Tr),Synthetic_Conclusion
0,00002A00010B1,temperatura v v predelu mastektomije je nekoli...,0,0,0,22,43,17,28,16,...,32.7,31.4,33.8,32.6,33.1,32.9,33.3,31.6,The temperature in the area of the mastectomy ...,No thermal changes detected.
1,00002A00010C1,v desni dojki je temperatura lepo razporejena ...,0,0,0,22,45,20,30,9,...,32.8,31.5,33.2,32.6,32.5,33.2,33.3,31.4,"In the right breast, the temperature is well d...",No thermal changes detected.
2,00002A00023C1,"1/ razporeditev temperature je asimetrična, ve...",1,0,0,21,53,25,0,-1,...,30.9,30.0,30.5,30.6,31.6,31.8,30.9,31.6,"1/ The temperature distribution is asymmetric,...",Slightly elevated temperature.
3,00002A00037C1,temperatura v obeh dojkah je pravilno porazdel...,0,0,0,25,54,24,0,-1,...,32.0,31.2,32.3,33.0,32.7,32.6,33.4,33.5,The temperature in both breasts is evenly dist...,No thermal changes detected.
4,00002A00037D1,"dojki sta srednje veliki, mehki, rahlo vozliča...",0,0,0,23,55,25,0,-1,...,31.4,31.7,33.3,32.5,33.6,33.4,33.7,33.1,"The breasts are medium-sized, soft, slightly n...",No thermal changes detected.

In [8]:
mwr_df_simple['y_binary'] = mwr_df_simple['r:Th'].apply(lambda x: 0 if x == 0 else 1)
y_class = mwr_df_simple['y_binary']

In [9]:
mwr_df_simple.to_csv('mwr_simple.csv', index=False)

### Temperature Based Conclusions

In [10]:
mwr_df_temps = add_synthetic_conclusion_from_temps(mwr_df.copy(deep=True))

In [11]:
print(mwr_df_temps['Synthetic_Conclusion'])

0        No thermal changes detected. Internal temps ex...
1        No thermal changes detected. Internal temps ex...
2        Very mild regional irregularities observed. Sl...
3                             No thermal changes detected.
4                             No thermal changes detected.
                               ...
24247    Significant thermal irregularities observed. M...
24248    Significant thermal irregularities observed. A...
24249                         No thermal changes detected.
24250                 Low-grade thermal anomalies present.
24251    Low-grade thermal anomalies present. Internal ...
Name: Synthetic_Conclusion, Length: 24236, dtype: object

In [12]:
mwr_df_temps.head()

,Examination ID,Conclusion,r:Th,Weight,Height,Ambient temperature,r:AgeInYears,Mammary diameter,Cycle,Day from the first day,...,R8 sk,L8 sk,R9 sk,L9 sk,T1 sk,T2 sk,R0 sk,L0 sk,Conclusion (Tr),Synthetic_Conclusion
0,00002A00010B1,temperatura v v predelu mastektomije je nekoli...,0,0,0,22,43,17,28,16,...,32.7,31.4,33.8,32.6,33.1,32.9,33.3,31.6,The temperature in the area of the mastectomy ...,No thermal changes detected. Internal temps ex...
1,00002A00010C1,v desni dojki je temperatura lepo razporejena ...,0,0,0,22,45,20,30,9,...,32.8,31.5,33.2,32.6,32.5,33.2,33.3,31.4,"In the right breast, the temperature is well d...",No thermal changes detected. Internal temps ex...
2,00002A00023C1,"1/ razporeditev temperature je asimetrična, ve...",1,0,0,21,53,25,0,-1,...,30.9,30.0,30.5,30.6,31.6,31.8,30.9,31.6,"1/ The temperature distribution is asymmetric,...",Very mild regional irregularities observed. Sl...
3,00002A00037C1,temperatura v obeh dojkah je pravilno porazdel...,0,0,0,25,54,24,0,-1,...,32.0,31.2,32.3,33.0,32.7,32.6,33.4,33.5,The temperature in both breasts is evenly dist...,No thermal changes detected.
4,00002A00037D1,"dojki sta srednje veliki, mehki, rahlo vozliča...",0,0,0,23,55,25,0,-1,...,31.4,31.7,33.3,32.5,33.6,33.4,33.7,33.1,"The breasts are medium-sized, soft, slightly n...",No thermal changes detected.

In [15]:
mwr_df_temps['y_binary'] = mwr_df_temps['r:Th'].apply(lambda x: 0 if x == 0 else 1)
y_class = mwr_df_temps['y_binary']

In [16]:
mwr_df_temps.to_csv('mwr_temps.csv', index=False)

### More Advanced Descriptions

In [7]:
mwr_df_adv = add_enhanced_synthetic_conclusions(mwr_df.copy(deep=True))

In [9]:
print(mwr_df_adv['Enhanced_Synthetic_Conclusion'])

0                                                                                                                                                                                                                                                             The temperature distribution shows physiological asymmetry within normal parameters. The difference between deep and superficial values indicates normal tissue metabolism. There are no signs of local hyperthermia or abnormal thermal activity. I advise regular self-examination of the breasts once a month and a systematic examination once a year.
1                                                                                                                                                                                                                                                              The temperature distribution shows physiological asymmetry within normal parameters. The difference between deep and superficial values indicates normal tissue metabolism. There are no signs of local hyperthermia or abnormal thermal activity. I recommend regular monthly self-examinations of the breasts and a systematic examination once a year.
2                                                                                                                                                                                                                                                                                                                                                                                                                                  The temperature in both breasts is well distributed with minor variations from the average. I recommend regular self-examination and a follow-up breast scan measurement in one year.
3                                                                                                                                                                                                                                                                        The temperature in both breasts is symmetrically distributed and within normal limits. The difference between deep and superficial values indicates normal tissue metabolism. There are no signs of local hyperthermia or abnormal thermal activity. I recommend regular self-examination once a month and systematic thermography in one year.
4                                                                                                                                                                                                                                                              The temperature distribution shows physiological asymmetry within normal parameters. The difference between deep and superficial values indicates normal tissue metabolism. There are no signs of local hyperthermia or abnormal thermal activity. I recommend regular monthly self-examinations of the breasts and a systematic examination once a year.
                                                                                                                                                                                                                                                                                                              ...
24247    The measured temperature shows marked asymmetry with significantly elevated thermal activity. The right breast demonstrates concerning thermal patterns. Multiple regions show significant thermal elevation: lower inner quadrant (+0.8°C), central region (+0.7°C). I recommend immediate clinical examination by a specialist doctor and comprehensive diagnostic evaluation including ultrasound and mammography if deemed necessary. A follow-up measurement should be scheduled within 2-4 weeks. In case of any palpable changes, discharge, or persistent symptoms, seek immediate clinical evaluation.
24248                The measured temperature shows marked asymmetry with significantly elevated thermal activity. The right breast demonstrates concerning thermal patterns. Multiple regions show significant thermal elevation: lower outer quadrant (+1.3°C). These thermal findings require immediate clinical correlation and comprehensive diagnostic workup including imaging studies. Urgent follow-up thermography recommended within 2-3 weeks, with earlier evaluation if clinical symptoms develop. In case of any palpable changes, discharge, or persistent symptoms, seek immediate clinical evaluation.
24249                                                                                                                                                                                                                                                                    The temperature in both breasts is symmetrically distributed and within normal limits. The difference between deep and superficial values indicates normal tissue metabolism. There are no signs of local hyperthermia or abnormal thermal activity. I recommend regular self-examination once a month and systematic thermography in one year.
24250                                                                                                                                                                                                                                                                                                                                                                                 The temperature distribution is asymmetric, but there are no signs of locally elevated metabolism. I recommend regular self-examinations, regular clinical examinations by an oncologist, and systematic measurements in one year.
24251                                                                                                                                                                                                                                                                                                                                                                                        The temperature distribution is asymmetric, but there are no signs of locally elevated metabolism. I recommend regular self-examinations and clinical evaluation within one year, with follow-up thermography as indicated.
Name: Enhanced_Synthetic_Conclusion, Length: 24236, dtype: object

In [20]:
mwr_df_adv['y_binary'] = mwr_df_adv['r:Th'].apply(lambda x: 0 if x == 0 else 1)
y_class = mwr_df_adv['y_binary']

In [21]:
mwr_df_adv.to_csv('mwr_adv.csv', index=False)

### Real Descriptions

In [8]:
# Remove column width truncation
pd.set_option('display.max_colwidth', None)

# Now print
print(mwr_df['Conclusion (Tr)'].head(30))

0                                                                                                                                                         The temperature in the area of the mastectomy is slightly higher than in the area of the left breast, but the difference between the deep and superficial values indicates rest or absence of proliferation. In the left breast, at the border of the lower quadrants, there is a typical hardening approximately 5mm in size, which is not thermally active. I recommend monitoring at one-month intervals. Otherwise, a follow-up in 6 months.
1                                                                                                                                                In the right breast, the temperature is well distributed and does not deviate from the average. In the left breast, a cooler area is visible around the nipple, specifically 0.9 degrees, which is still within normal limits. The left breast is also quite nodular, particularly in the cooler area and at the boundary of the outer quadrants. I recommend self-examination once a month and a systematic check-up in one year or sooner if necessary.
2                                                                                                                                                                                                                                                                                                                                                    1/ The temperature distribution is asymmetric, but there are no signs of local hyperthermia in the breasts. I recommend regular self-examinations, a clinical examination by an oncologist within one year, and a systematic examination in one year.
3                                                                                                                                                                                                                                                                   The temperature in both breasts is evenly distributed and symmetrical. There are no signs of specific pathology. Clinically, the breasts are abundant, soft, and free of suspicious lumps. The axillae and supraclavicular areas are clear. I recommend regular self-examinations once a month and microwave thermography once a year.
4                                                                                                                         The breasts are medium-sized, soft, slightly nodular, and non-tender. Clinically, the tissue is denser primarily in the outer quadrants, and individual nodular formations can be slightly felt, but they are not tender. The temperature in the breasts is symmetrically distributed and within normal limits, not indicating any pathology. The axillas and supraclavicular areas are clear. I recommend self-examination once a month and a systematic examination in a year.
5                                                                                                                                                                                                                                                                                                 1/ The measured temperature in both breasts is symmetrical and at the recommended temperature level. There are no signs of local hyperthermia. I advise regular self-examination once a month, a clinical examination by a specialist within one year, and a systematic examination with us in one year.
6                                                                                                                                                                                                                                                                                                                           The temperature in the breast area is within the limits of physiological symmetry, both in depth and on the surface. There are no signs of a proliferative process. I advise regular self-examination immediately after menstruation and a systematic examination once a year.
7                                                                                                                                                                                        The temperature in the breast area is correctly and symmetrically distributed. There are no signs of specific pathology. The breasts are symmetrical, abundant, smooth on the surface, slightly grainy in depth, and without characteristic lumps. The axillary and supraclavicular regions are free. I advise regular self-examinations immediately after menstruation and a systematic examination once a year.
8                                                                                                                                                                                                                                                                           1/ The distribution is asymmetrical, but there are no signs of locally elevated metabolism in the breasts. I recommend monthly self-examination and a systematic check-up in one year. In case of worsening pain, I advise a clinical examination by an oncologist and possibly an early measurement according to his opinion.
9                                                                                                                                                                                                                                                                                                                                                The breasts are symmetrical. Clinically, they are medium-sized and not sensitive to touch. The axillae and supraclavicular areas are clear. I advise a self-examination of the breasts once a month after menstruation. A systematic checkup once a year.
10                                                                                                                                                                                                                                                                                                                                               The breasts are symmetrical. Clinically, they are medium-sized and not sensitive to touch. The axillae and supraclavicular areas are clear. I advise a self-examination of the breasts once a month after menstruation. A systematic checkup once a year.
11                                                                                                                                                                                                                               The breasts are small, soft, and without lumps, except in the left breast, where small nodules can be felt. The temperature in both breasts is symmetrically distributed and does not indicate any pathology. The axillae and supraclavicular areas are clear. I recommend regular self-examination of the breasts once a month and a systematic examination once a year.
12                                                                                                                                                                                                                                                                                                                                                                                1. The temperature in both breasts is symmetrically distributed. No signs of local hyperthermia are detected. I recommend regular self-examination of the breasts once a month and a systematic examination in one year.
13                                                                                                                                                                                                                                                                                                                                            1/The temperature distribution is symmetrically distributed. No signs of localized hyperthermia in the breasts are detected. I recommend regular self-examinations, regular clinical examinations by an oncologist, and systematic measurements in one year.
14                                                                                                                                                                                                                                                                                                                                                                     1/the temperature distribution does not indicate signs of localized increased metabolism in breast tissue. I advise regular self-examinations, regular clinical checks with an oncologist, and systematic measurements in one year.
15                                                                                                                                                                                                                                                                           1/The temperature distribution does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examinations, regular clinical check-ups with an oncologist, and systematic measurement in one year. In case of typical, visible changes or prolonged pain, seek early consultation as agreed.
16                                                                                                                                                                                                                                                                           1/The temperature distribution does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examinations, regular clinical check-ups with an oncologist, and systematic measurement in one year. In case of typical, visible changes or prolonged pain, seek early consultation as agreed.
17                                                                                                                                                                                                                                                                                                                                          1/The temperature distribution does not indicate signs of elevated metabolism. I advise regular self-examination, a clinical examination by an oncologist within one year, and a systematic examination after one year. In case of changes, do it prematurely.
18                                                                                                                                                                                                                                                             The temperature in the breast area is somewhat irregular, but shows a symmetrical pattern. Clinically, the breasts are small, symmetrical, soft, and free of pathological lumps. The axillary and supraclavicular regions are clear. I recommend regular monthly self-examinations of the breasts and a systematic examination once a year.
19    3/ The measured temperature in both breasts is asymmetrical and high. The left breast is warmer - more active on the outer edge of the breast in the upper inner quadrant (+0.7 degrees), at the boundary of the upper quadrant (+1.8 degrees), in the upper outer quadrant (+1.3 degrees), at the boundary of the outer quadrant (+1.2 degrees), and in the lower outer quadrant (+0.6 degrees). The surface is cool. I recommend a clinical examination by a specialist doctor and further diagnostic evaluation as per the doctor's opinion, as well as a follow-up measurement within one month.
20                                                                                                                                                                                                                                                                                                                                                                                                        3/ The temperature is also higher than the recommended temperature level while in a sitting position. I advise a clinical examination by a specialized physician and possibly further treatment.
21                                                                                                                                                                                                                                                                                                                      2/ The measured temperature in both breasts is asymmetric. The left breast is warmer compared to the right. The hottest spot is in the upper inner quadrant of the left breast (asymmetry: 1 degree). I recommend self-examination once a month and a remeasurement in 4-6 months.
22                                                                                                                                                                                                                                                                                                                                                                                                                                       1/the measured temperature does not indicate signs of increased metabolism in breast tissue. I advise regular self-examinations and a re-measurement in one year.
23                                                                                                                                                                                                                       The measured temperature is significantly higher than the recommended level, but there are no signs of locally elevated metabolism in breast tissue. We recommend a follow-up in 6-12 months (02. 2011-08.2011). During this period, we advise monthly self-examinations. In case of noticeable, visible changes, discharge, or prolonged pain, an earlier check-up is necessary.
24                                                                                                 The 3 dex in sin, the 2 sin 1,2,3/ the measured temperature is entirely higher than the recommended level and is asymmetrically distributed, exceeding the recommended value. Therefore, we recommend repeating the measurement in 6 months (02.2012). During this period, we advise monthly self-examinations and preventive ultrasound with a specialist, and, if necessary, also a mammogram. In case of noticeable, visible changes, discharge, or lingering pain, please seek an earlier check-up.
25                                                                                                                                                                                                                       The measured temperature does not indicate signs of locally increased metabolism. I recommend a follow-up in 1 year (07. 2013). During this period, we advise monthly self-examinations and a preventive ultrasound with a specialist, and a mammogram if necessary. In the case of palpable, visible changes, discharge, or prolonged pain, please schedule an earlier check-up.
26                                                                                                                                                      Measured temperature asymmetrically distributed, currently above the recommended values. We recommend repeating the measurement 6 months after the removal of the pacifier. During this period, we advise monthly self-examinations and preventive check-ups with a specialist (an invitation is expected soon). In case of any notable visible changes, discharge, prolonged pain, or questionable medical opinion, an early check-up is advised.
27                                                                                                                                                                                          1/the measured temperature does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examination, regular recommended clinical examinations by a specialist, and additional preventive diagnostics as deemed necessary, as well as a follow-up breast scan measurement in one year. In case of findings, visible changes, or prolonged pain, seek an appointment sooner.
28                                                                                                                                                                                                                        1/The measured temperature does not indicate signs of locally increased metabolism in the breast tissue. We recommend regular self-examination and a follow-up breast scan measurement in one year. In the case of noticeable, visible changes, discharge, or worsening pain, we recommend a clinical examination by a specialist doctor and an earlier breast scan measurement.
29                                                                                                                                                                                                                                                 The measured temperature does not indicate signs of locally increased metabolism in breast tissue. We recommend regular self-examination and a follow-up breast scan in 2 years (April 2011). In case of notable, visible changes, discharge, or persistent pain, we recommend a clinical examination by a specialist and an earlier breast scan check.
Name: Conclusion (Tr), dtype: object

In [23]:
mwr_df['Conclusion (Tr)'] = mwr_df['Conclusion (Tr)'].apply(preprocess_conclusion)

In [24]:
mwr_df.shape[0]

24236

In [25]:
# remove rows with empty strings
mwr_df = mwr_df[mwr_df['Conclusion (Tr)'] != ""].copy()
mwr_df.shape[0]

24162

In [26]:
print(mwr_df['Conclusion (Tr)'].head(30))

0                                                                                                                                                      The temperature in the area of the mastectomy is slightly higher than in the area of the left breast, but the difference between the deep and superficial values indicates rest or absence of proliferation. In the left breast, at the border of the lower quadrants, there is a typical hardening approximately 5mm in size, which is not thermally active. I recommend monitoring at one-month intervals. Otherwise, a follow-up in 6 months.
1                                                                                                                                             In the right breast, the temperature is well distributed and does not deviate from the average. In the left breast, a cooler area is visible around the nipple, specifically 0.9 degrees, which is still within normal limits. The left breast is also quite nodular, particularly in the cooler area and at the boundary of the outer quadrants. I recommend self-examination once a month and a systematic check-up in one year or sooner if necessary.
2                                                                                                                                                                                                                                                                                                                                                    The temperature distribution is asymmetric, but there are no signs of local hyperthermia in the breasts. I recommend regular self-examinations, a clinical examination by an oncologist within one year, and a systematic examination in one year.
3                                                                                                                                                                                                                                                                The temperature in both breasts is evenly distributed and symmetrical. There are no signs of specific pathology. Clinically, the breasts are abundant, soft, and free of suspicious lumps. The axillae and supraclavicular areas are clear. I recommend regular self-examinations once a month and microwave thermography once a year.
4                                                                                                                      The breasts are medium-sized, soft, slightly nodular, and non-tender. Clinically, the tissue is denser primarily in the outer quadrants, and individual nodular formations can be slightly felt, but they are not tender. The temperature in the breasts is symmetrically distributed and within normal limits, not indicating any pathology. The axillas and supraclavicular areas are clear. I recommend self-examination once a month and a systematic examination in a year.
5                                                                                                                                                                                                                                                                                                 The measured temperature in both breasts is symmetrical and at the recommended temperature level. There are no signs of local hyperthermia. I advise regular self-examination once a month, a clinical examination by a specialist within one year, and a systematic examination with us in one year.
6                                                                                                                                                                                                                                                                                                                        The temperature in the breast area is within the limits of physiological symmetry, both in depth and on the surface. There are no signs of a proliferative process. I advise regular self-examination immediately after menstruation and a systematic examination once a year.
7                                                                                                                                                                                     The temperature in the breast area is correctly and symmetrically distributed. There are no signs of specific pathology. The breasts are symmetrical, abundant, smooth on the surface, slightly grainy in depth, and without characteristic lumps. The axillary and supraclavicular regions are free. I advise regular self-examinations immediately after menstruation and a systematic examination once a year.
8                                                                                                                                                                                                                                                                           The distribution is asymmetrical, but there are no signs of locally elevated metabolism in the breasts. I recommend monthly self-examination and a systematic check-up in one year. In case of worsening pain, I advise a clinical examination by an oncologist and possibly an early measurement according to his opinion.
9                                                                                                                                                                                                                                                                                                                                             The breasts are symmetrical. Clinically, they are medium-sized and not sensitive to touch. The axillae and supraclavicular areas are clear. I advise a self-examination of the breasts once a month after menstruation. A systematic checkup once a year.
10                                                                                                                                                                                                                                                                                                                                            The breasts are symmetrical. Clinically, they are medium-sized and not sensitive to touch. The axillae and supraclavicular areas are clear. I advise a self-examination of the breasts once a month after menstruation. A systematic checkup once a year.
11                                                                                                                                                                                                                            The breasts are small, soft, and without lumps, except in the left breast, where small nodules can be felt. The temperature in both breasts is symmetrically distributed and does not indicate any pathology. The axillae and supraclavicular areas are clear. I recommend regular self-examination of the breasts once a month and a systematic examination once a year.
12                                                                                                                                                                                                                                                                                                                                                                             1. The temperature in both breasts is symmetrically distributed. No signs of local hyperthermia are detected. I recommend regular self-examination of the breasts once a month and a systematic examination in one year.
13                                                                                                                                                                                                                                                                                                                                           The temperature distribution is symmetrically distributed. No signs of localized hyperthermia in the breasts are detected. I recommend regular self-examinations, regular clinical examinations by an oncologist, and systematic measurements in one year.
14                                                                                                                                                                                                                                                                                                                                                                    The temperature distribution does not indicate signs of localized increased metabolism in breast tissue. I advise regular self-examinations, regular clinical checks with an oncologist, and systematic measurements in one year.
15                                                                                                                                                                                                                                                                          The temperature distribution does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examinations, regular clinical check-ups with an oncologist, and systematic measurement in one year. In case of typical, visible changes or prolonged pain, seek early consultation as agreed.
16                                                                                                                                                                                                                                                                          The temperature distribution does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examinations, regular clinical check-ups with an oncologist, and systematic measurement in one year. In case of typical, visible changes or prolonged pain, seek early consultation as agreed.
17                                                                                                                                                                                                                                                                                                                                         The temperature distribution does not indicate signs of elevated metabolism. I advise regular self-examination, a clinical examination by an oncologist within one year, and a systematic examination after one year. In case of changes, do it prematurely.
18                                                                                                                                                                                                                                                          The temperature in the breast area is somewhat irregular, but shows a symmetrical pattern. Clinically, the breasts are small, symmetrical, soft, and free of pathological lumps. The axillary and supraclavicular regions are clear. I recommend regular monthly self-examinations of the breasts and a systematic examination once a year.
19    The measured temperature in both breasts is asymmetrical and high. The left breast is warmer - more active on the outer edge of the breast in the upper inner quadrant (+0.7 degrees), at the boundary of the upper quadrant (+1.8 degrees), in the upper outer quadrant (+1.3 degrees), at the boundary of the outer quadrant (+1.2 degrees), and in the lower outer quadrant (+0.6 degrees). The surface is cool. I recommend a clinical examination by a specialist doctor and further diagnostic evaluation as per the doctor's opinion, as well as a follow-up measurement within one month.
20                                                                                                                                                                                                                                                                                                                                                                                                        The temperature is also higher than the recommended temperature level while in a sitting position. I advise a clinical examination by a specialized physician and possibly further treatment.
21                                                                                                                                                                                                                                                                                                                      The measured temperature in both breasts is asymmetric. The left breast is warmer compared to the right. The hottest spot is in the upper inner quadrant of the left breast (asymmetry: 1 degree). I recommend self-examination once a month and a remeasurement in 4-6 months.
22                                                                                                                                                                                                                                                                                                                                                                                                                                      The measured temperature does not indicate signs of increased metabolism in breast tissue. I advise regular self-examinations and a re-measurement in one year.
23                                                                                                                                                                                                                    The measured temperature is significantly higher than the recommended level, but there are no signs of locally elevated metabolism in breast tissue. We recommend a follow-up in 6-12 months (02. 2011-08.2011). During this period, we advise monthly self-examinations. In case of noticeable, visible changes, discharge, or prolonged pain, an earlier check-up is necessary.
24                                                                                                                                 The measured temperature is entirely higher than the recommended level and is asymmetrically distributed, exceeding the recommended value. Therefore, we recommend repeating the measurement in 6 months (02.2012). During this period, we advise monthly self-examinations and preventive ultrasound with a specialist, and, if necessary, also a mammogram. In case of noticeable, visible changes, discharge, or lingering pain, please seek an earlier check-up.
25                                                                                                                                                                                                                    The measured temperature does not indicate signs of locally increased metabolism. I recommend a follow-up in 1 year (07. 2013). During this period, we advise monthly self-examinations and a preventive ultrasound with a specialist, and a mammogram if necessary. In the case of palpable, visible changes, discharge, or prolonged pain, please schedule an earlier check-up.
26                                                                                                                                                   Measured temperature asymmetrically distributed, currently above the recommended values. We recommend repeating the measurement 6 months after the removal of the pacifier. During this period, we advise monthly self-examinations and preventive check-ups with a specialist (an invitation is expected soon). In case of any notable visible changes, discharge, prolonged pain, or questionable medical opinion, an early check-up is advised.
27                                                                                                                                                                                         The measured temperature does not indicate signs of locally increased metabolism in breast tissue. I advise regular self-examination, regular recommended clinical examinations by a specialist, and additional preventive diagnostics as deemed necessary, as well as a follow-up breast scan measurement in one year. In case of findings, visible changes, or prolonged pain, seek an appointment sooner.
28                                                                                                                                                                                                                       The measured temperature does not indicate signs of locally increased metabolism in the breast tissue. We recommend regular self-examination and a follow-up breast scan measurement in one year. In the case of noticeable, visible changes, discharge, or worsening pain, we recommend a clinical examination by a specialist doctor and an earlier breast scan measurement.
29                                                                                                                                                                                                                                              The measured temperature does not indicate signs of locally increased metabolism in breast tissue. We recommend regular self-examination and a follow-up breast scan in 2 years (April 2011). In case of notable, visible changes, discharge, or persistent pain, we recommend a clinical examination by a specialist and an earlier breast scan check.
Name: Conclusion (Tr), dtype: object

In [27]:
# check all values are strings
non_string_count = mwr_df['Conclusion (Tr)'].apply(lambda x: not isinstance(x, str)).sum()

print("Number of non-string values:", non_string_count)

Number of non-string values: 0

### Binary encoding

In [28]:
mwr_df['y_binary'] = mwr_df['r:Th'].apply(lambda x: 0 if x == 0 else 1)
y_class = mwr_df['y_binary']

In [29]:
mwr_df.to_csv('mwr.csv', index=False)